### ISSUE TITLE
Crash on Meteor 1.4 beta 9

### ISSUE THREAD

**Issue by puedesleerlo** [Urigo/meteor-static-html-compiler#11]
Hello, when I add static-html-compiler into a project with Meteor 1.4 beta 9 I get this error:

```
ReferenceError: Plugin is not defined
W20160711-15:32:58.611(-5)? (STDERR)     at meteorInstall.node_modules.meteor.caching-compiler.caching-compiler.js (packages/caching-compiler/caching-compiler.js:1:12)
W20160711-15:32:58.612(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160711-15:32:58.614(-5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160711-15:32:58.614(-5)? (STDERR)     at /home/alejandro/Web/TDGA2/.meteor/local/build/programs/server/packages/caching-compiler.js:691:1
W20160711-15:32:58.614(-5)? (STDERR)     at /home/alejandro/Web/TDGA2/.meteor/local/build/programs/server/packages/caching-compiler.js:704:3
W20160711-15:32:58.615(-5)? (STDERR)     at /home/alejandro/Web/TDGA2/.meteor/local/build/programs/server/boot.js:297:10
W20160711-15:32:58.615(-5)? (STDERR)     at Array.forEach (native)
W20160711-15:32:58.615(-5)? (STDERR)     at Function._.each._.forEach (/home/alejandro/.meteor/packages/meteor-tool/.1.4.0-beta.9.qfg6kr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)                                                                                                                         
W20160711-15:32:58.616(-5)? (STDERR)     at /home/alejandro/Web/TDGA2/.meteor/local/build/programs/server/boot.js:133:5
```

**Comment by dotansimha** [comment]
Hi @puedesleerlo ,
Please try the latest version (`0.1.1`).

**Comment by kamilkisiela** [comment]
`v0.1.1` works with `Meteor@1.4-RC.1`, I checked.

Please try to update to the latest release available, if it won't help then we will come up with something! :)

**Comment by kamilkisiela** [comment]
@mention me if problem still occurs.

**Comment by puedesleerlo** [comment]
Thank you very much, it works
